module.exports = {
	name: 'rishi_mute',
	description: 'Chance to mute rishi.',
	execute(message, Discord, client) {
        if (Math.random() < 0.10)
		{
			message.delete();
			message.author.send('WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS WHAMS <@557379287460741143>');
		}
    }
}
